name: test
on:
  push:
    branches:
      - master
    paths:
      - '**.go'
      - '**.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**.go'
      - '**.yml'
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['^1.14', '^1.15', '^1.16', '^1.17']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Get dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          # Required by Fyne
          sudo apt-get update && sudo apt-get -y install libgl1-mesa-dev xorg-dev
      - name: Cache the Go modules
        uses: actions/cache@v3.0.3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download the Go modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download
      - name: Test
        run: go test -v -race ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          # Required by Fyne
          sudo apt-get update && sudo apt-get -y install libgl1-mesa-dev xorg-dev
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ~/bin v1.43.0
      - name: Run golangci-lint
        run: ~/bin/golangci-lint run --out-format github-actions
