name: test
on: push
jobs:
  test:
    strategy:
      matrix:
        go: ['1.13.x', '1.14.x']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: Get dependencies
        # Required by Fyne
        run: |
          sudo apt install libgl1-mesa-dev xorg-dev
      - name: Test
        run: go test -v -race ./...
